# syntax=docker/dockerfile:1

# example docker run:
# docker run --env=PORT_HTTP=8000 --env=PORT_HTTPS=8008 --env="SSL_CERT_SUBJ=/C=DE/ST=Bavaria/O=Feuerwehr XYZ/CN=firenotifier.example.com" --env="BEARER_TOKENS_JSON={ \"aagkdd\": \"testapp\" }" -p 8008:8008 -p 8000:8000 -d ghcr.io/as19git67/firenotifier:main

FROM node:18-alpine
WORKDIR /app
COPY . .

VOLUME ["/data"]

ARG ARG_PORT_HTTP="5002"
ENV PORT_HTTP=${ARG_PORT_HTTP}
ARG ARG_PORT_HTTPS="5052"
ENV PORT_HTTPS=${ARG_PORT_HTTPS}
ARG ARG_SSL_CERT_SUBJ=""
ENV SSL_CERT_SUBJ=${ARG_SSL_CERT_SUBJ}

ARG ARG_MIN_WAIT_MINUTES_TO_NOTIFY_SAME_GROUP="2"
ENV MIN_WAIT_MINUTES_TO_NOTIFY_SAME_GROUP=${ARG_MIN_WAIT_MINUTES_TO_NOTIFY_SAME_GROUP}

ARG ARG_SYNCDESTINATION_URL=""
ENV SYNCDESTINATION_URL=${ARG_SYNCDESTINATION_URL}
ARG ARG_SYNCDESTINATION_BEARERTOKEN=""
ENV SYNCDESTINATION_BEARERTOKEN=${ARG_SYNCDESTINATION_BEARERTOKEN}
ARG ARG_SYNCDESTINATION_ACCEPTSELFSIGNEDCERTIFICATE=false
ENV SYNCDESTINATION_ACCEPTSELFSIGNEDCERTIFICATE=${ARG_SYNCDESTINATION_ACCEPTSELFSIGNEDCERTIFICATE}

ARG ARG_SMS_CLIENT_ID=""
ENV SMS_CLIENT_ID=${ARG_SMS_CLIENT_ID}
ARG ARG_SMS_CLIENT_SECRET=""
ENV SMS_CLIENT_SECRET=${ARG_SMS_CLIENT_SECRET}
ARG ARG_SMS_SENDER_NR=""
ENV SMS_SENDER_NR=${ARG_SMS_SENDER_NR}
ARG ARG_SMS_VALIDITY_HOURS="26"
ENV SMS_VALIDITY_HOURS=${ARG_SMS_VALIDITY_HOURS}
ARG ARG_SMS_WAIT_FOR_STATUS="600"
ENV SMS_WAIT_FOR_STATUS=${ARG_SMS_WAIT_FOR_STATUS}
ARG ARG_EMAIL_SMTP_SENDER_EMAIL="alarm@example.com"
ENV EMAIL_SMTP_SENDER_EMAIL=${ARG_EMAIL_SMTP_SENDER_EMAIL}
ARG ARG_EMAIL_SMTP_USERNAME="alarm@example.com"
ENV EMAIL_SMTP_USERNAME=${ARG_EMAIL_SMTP_USERNAME}
ARG ARG_EMAIL_SMTP_PASSWORD="geheim"
ENV EMAIL_SMTP_PASSWORD=${ARG_EMAIL_SMTP_PASSWORD}
ARG ARG_EMAIL_SMTP_USE_SSL=FALSE
ENV EMAIL_SMTP_USE_SSL=${ARG_EMAIL_SMTP_USE_SSL}
ARG ARG_EMAIL_SMTP_SERVER_HOST="smtp.example.com"
ENV EMAIL_SMTP_SERVER_HOST=${ARG_EMAIL_SMTP_SERVER_HOST}
ARG ARG_EMAIL_SMTP_SERVER_PORT="587"
ENV EMAIL_SMTP_SERVER_PORT=${ARG_EMAIL_SMTP_SERVER_PORT}
ARG ARG_EMAIL_POSTMASTER_ADDRESS="postmaster@example.com"
ENV EMAIL_POSTMASTER_ADDRESS=${ARG_EMAIL_POSTMASTER_ADDRESS}



RUN yarn install --production
RUN apk update && apk add --no-cache openssl tzdata

ARG ARG_TZ="Europe/Berlin"
ENV TZ=${ARG_TZ}

CMD ["/bin/sh", "./start.sh"]

EXPOSE $PORT_HTTP
EXPOSE $PORT_HTTPS
